import { NextResponse } from "next/server";
import WithDriverQuote from "@/models/withdriverqoute";
import {dbConnect} from "@/lib/dbConnect"; // or wherever your db connect function lives
import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail", // or host/port for other providers
  auth: {
    user: process.env.SMTP_USER,   // your-address@gmail.com
    pass: process.env.SMTP_PASS,   // app-password / OAuth2 token
  },
});
export async function POST(req: Request) {
  try {
    await dbConnect();
    const body = await req.json();

    const newQuote = await WithDriverQuote.create(body);
    const filteredEntries = Object.entries(body).filter(
      ([, v]) => v !== "" && v !== "-"
    );

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 6px; overflow: hidden;">
        <div style="background: #000; color: white; padding: 16px; text-align: center; font-size: 20px; font-weight: bold;">
          You have got a new With Driver Quote submission
        </div>
        <table style="width: 100%; border-collapse: collapse;">
          <tbody>
            ${filteredEntries
              .map(
                ([key, value]) => `
                  <tr>
                    <td style="padding: 10px 14px; border-bottom: 1px solid #eee; font-weight: 600; text-transform: capitalize;">
                      ${key.replace(/([A-Z])/g, " $1")}
                    </td>
                    <td style="padding: 10px 14px; border-bottom: 1px solid #eee;">
                      ${Array.isArray(value) ? value.join(", ") : value}
                    </td>
                  </tr>
                `
              )
              .join("")}
          </tbody>
        </table>
        <div style="background: #f9f9f9; padding: 10px 14px; font-size: 12px; color: #777; text-align: center;">
          This message was automatically generated by your website.
        </div>
      </div>
    `;
    await transporter.sendMail({
      from: `"CCS Luxury Chauffeurs" <${process.env.SMTP_USER}>`, 
      to: process.env.NOTIFY_EMAIL,                    
      subject: "With Driver Quote Form",
      html: htmlContent,
    });

    return NextResponse.json(
      { success: true, message: "Driver quote submitted", data: newQuote },
      { status: 201 }
    );
  } catch (error) {
    console.error("Error saving driver quote:", error);
    return NextResponse.json(
      { success: false, message: "Failed to submit driver quote" },
      { status: 500 }
    );
  }
}
