import { NextResponse } from "next/server";
import {dbConnect} from "@/lib/dbConnect";
import LetsConnect from "@/models/Letsconnect";

import type { NextRequest } from "next/server";
import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail", // or host/port for other providers
  auth: {
    user: process.env.SMTP_USER,   // your-address@gmail.com
    pass: process.env.SMTP_PASS,   // app-password / OAuth2 token
  },
});
export async function POST(req: NextRequest) {
  try {
    await dbConnect();
    const body = await req.json();
    const { name, phone, email, address, details } = body;

    if (!name || !phone || !email || !address) {
      return NextResponse.json({ error: "All fields are required" }, { status: 400 });
    }

    const entry = await LetsConnect.create({ name, phone, email, address, details });
    const data = { name, phone, email, address, details };
    const filteredEntries = Object.entries(data).filter(
      ([, v]) => v !== "" && v !== "-"
    );

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 6px; overflow: hidden;">
        <div style="background: #000; color: white; padding: 16px; text-align: center; font-size: 20px; font-weight: bold;">
          You have got a new Let's Connect submission
        </div>
        <table style="width: 100%; border-collapse: collapse;">
          <tbody>
            ${filteredEntries
              .map(
                ([key, value]) => `
                  <tr>
                    <td style="padding: 10px 14px; border-bottom: 1px solid #eee; font-weight: 600; text-transform: capitalize;">
                      ${key.replace(/([A-Z])/g, " $1")}
                    </td>
                    <td style="padding: 10px 14px; border-bottom: 1px solid #eee;">
                      ${Array.isArray(value) ? value.join(", ") : value}
                    </td>
                  </tr>
                `
              )
              .join("")}
          </tbody>
        </table>
        <div style="background: #f9f9f9; padding: 10px 14px; font-size: 12px; color: #777; text-align: center;">
          This message was automatically generated by your website.
        </div>
      </div>
    `;
    await transporter.sendMail({
      from: `"CCS Luxury Chauffeurs" <${process.env.SMTP_USER}>`, 
      to: process.env.NOTIFY_EMAIL,                    
      subject: "Let's Conenct Submission",
      html: htmlContent,
    });
    return NextResponse.json({ success: true, message: "Form submitted successfully", entry });
  } catch (error) {
    console.error("Error submitting Let's Connect form:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
